### ISSUE TITLE
Kidding

### ISSUE THREAD

**Issue by forsigner** [unasuke/do-not-use-atom#2]
You are kidding, ha ha~

**Comment by unasuke** [comment]
Yes. This atom plugin is a joke. :stuck_out_tongue:
I think that vim (and emacs) is an editor for programmers. Atom is so too.

But, atom has some problems.
example...
- Too slow startup.
- UI needs mouse.

That's not serious but make me frustrating.

This plugin purpose...
1. use vim
2. learn javascript(coffescript) programming

Thank you your comment!  :laughing:
