### ISSUE TITLE
Very important issue!

### ISSUE THREAD

**Issue by Kosai106** [unasuke/do-not-use-atom#4]
It tells me not to use Atom.
How do I fix this?

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

`/Sarcasm`

**Comment by unasuke** [comment]
Ah...What's mean? :open_mouth:

**Comment by Kosai106** [comment]
It's a joke, don't worry @unasuke :smile:

**Comment by unasuke** [comment]
:hand: :sunglasses:

**Comment by Alhadis** [comment]
`s/do not //i`
